### ISSUE TITLE
Editor is not opened even if it is in PATH

### ISSUE THREAD

**Issue by egor-khanko** [torbratsberg/noted#1]
When I try to create a new note, `noted` crashes and display this error:
`2022/09/27 19:16:45 exec: "subl -w": executable file not found in $PATH`
It also breaks terminal, but this is another issue (and maybe it's zsh's issue)
My `EDITOR` is set to "**subl -w**", but looks like noted could not see it somehow. I can launch `subl` from any place in terminal, so error seems incorrect)

**Comment by torbratsberg** [comment]
Pushed a new commit now that puts the args from `$EDITOR` into the args parameter of `cmd.exec`, I think this should fix it. Could you try checking out my newest commit?

**Comment by egor-khanko** [comment]
Hey! Sorry, didn't notice your reply right away...
Yep, this is working now, thanks a lot for quick response/fix!:smiley:
